[platformio]
default_envs = esp32dev

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = min_spiffs.csv
extra_scripts = pre:scripts/build_info.py

lib_deps =
    bodmer/TFT_eSPI
    https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
    bblanchon/ArduinoJson
    https://github.com/Bodmer/TJpg_Decoder.git

build_flags =
    -D USER_SETUP_LOADED
    -D ILI9341_DRIVER
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=320
    -D TFT_MISO=12
    -D TFT_MOSI=13
    -D TFT_SCLK=14
    -D TFT_CS=15
    -D TFT_DC=2
    -D TFT_RST=-1
    -D DASHBOARD_BACKLIGHT_PIN=21
    -D TFT_RGB_ORDER=TFT_BGR
    -D SPI_FREQUENCY=40000000
    -D SPI_READ_FREQUENCY=20000000
    -D LOAD_GLCD

[env:esp32dev]
upload_port = COM3
monitor_port = COM3

[env:esp32dev-ota]
upload_protocol = espota
upload_port = 192.168.1.18
